### ISSUE TITLE
Robust code

### ISSUE THREAD

**Issue by szepeviktor** [strata/frontend#50]
Please consider running static analysis `phpstan analyse src/ -l 0`
Levels go up to 8.

On Level 0 you'll be shown 27 **trivial** errors 💣

**Comment by simonrjones** [comment]
thanks @szepeviktor - PHP Stan is a good idea, we'll try it out. We are planning a major re-organisation of the codebase so we're aware there are some less than ideal areas that need overhauling. We're hoping to do this in the next 1-2 months to start to get towards a 1.0 release.

**Comment by szepeviktor** [comment]
On Level 0 currently there are 27 problems

- Level 2 poorly written code
- Level 4 average code
- Level 5+ Robust code :)

**Comment by simonrjones** [comment]
Added PHPStan in latest code release, useful tool thanks.
