### ISSUE TITLE
composer.lock file is .gitignored

### ISSUE THREAD

**Issue by sean-dunwoody** [strata/frontend#81]
The composer.lock file seems to be gitignored, but is it not best practise to include the gitignore to ensure that packages installed are the same across different machines/environments?

**Comment by simonrjones** [comment]
As far as I know, you should include composer.lock in an end project, but not an open source library like this. The composer.json file is intended to contain enough info to load the necessary files.

Lock files are used to ensure a project runs exactly the same version, you don't want to restrict any projects using Strata like this.
